apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: system
  sources:
    - repoURL: "https://metallb.github.io/metallb"
      targetRevision: 0.13.*
      chart: metallb
      helm:
        valuesObject:
    - repoURL: "https://github.com/gensokyo-zone/infrastructure"
      path: k8s/system/metallb/manifests
      targetRevision: main
  destination:
    namespace: metallb-system
    name: in-cluster
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
  ignoreDifferences:
  - group: "apiextensions.k8s.io"
    kind: CustomResourceDefinition
    name: bgppeers.metallb.io
    jsonPointers:
    - /spec/conversion/webhook/clientConfig/caBundle
  - group: "apiextensions.k8s.io"
    kind: CustomResourceDefinition
    name: addresspools.metallb.io
    jsonPointers:
    - /spec/conversion/webhook/clientConfig/caBundle
