apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- project.yaml
- flannel
- argocd
- coredns
- local-path-storage
- sops-secrets-operator
- cloudflare-operator
- metallb
- traefik
- dex