apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-storage
  namespace: argocd
spec:
  project: system
  source:
    repoURL: "https://github.com/gensokyo-zone/infrastructure"
    path: k8s/system/local-path-provisioner/manifests
  targetRevision: main
  helm:
    valuesObject:
  destination:
    namespace: local-path-storage
    name: in-cluster
  syncPolicy:
    syncOptions:
      - ServerSideApply=true