apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system
  namespace: argocd
spec:
  destination:
    namespace: default
    name: in-cluster
  project: system
  source:
    repoURL: "https://github.com/gensokyo-zone/infrastructure"
    path: k8s/system
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true