apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: system
  source:
    repoURL: "https://argoproj.github.io/argo-helm/"
    targetRevision: 5.52.*
    chart: argo-cd
    helm:
      valuesObject:
        server:
          service:
            type: LoadBalancer
          inigress:
            enabled: true
  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true