apiVersion: ENC[AES256_GCM,data:6tM=,iv:xSPYVxWwySOWXMDG0xYTHpIxzET23JywZF5FAkohQmU=,tag:7VB2Y8ZhbE/cXGn3KpxV8Q==,type:str]
data:
    CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:9FWV5dWj5Qll6zq81Y0W8Wi0orctjl4XjAXFLaUfvD6utUVHIGjN+WyRTAwZd3Rvih7TdQ==,iv:rSMSf59OumsNxnsdjODwCrQpedtF/vLiIy55oBHR0+0=,tag:AhNG3Y+a/sUzq4dsWukKBg==,type:str]
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:5KFCNknZLBBNM5vpd0oMQEQIstmGFnSG+L+vKa5rmjc2oZCDkGWeI23c6W3OzDAyZMPoO4v9so0=,iv:wDT36I1wEi3oWAgmC7Bwm9PyCPh4mCdFhSghqklj6tw=,tag:+I5rOGQrPbSqxRF/9l8atw==,type:str]
kind: ENC[AES256_GCM,data:VwEWynNq,iv:Y0IgB4CDzmFxTQ/PLhfqjMQW9w6guI/t0nNhGl2urg0=,tag:84HRARvuQW+P8ooxY4Q6/Q==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:ZuNsbuZKHhhK+/bVYAkk75Jy,iv:f28cglBsB0vo6EkmnlCTK5MOHDDEcJlS29GtzY6PRgg=,tag:ZJU5vI2Q2a2t5gPfDdlDyw==,type:str]
    namespace: ENC[AES256_GCM,data:vN1XQTOhmTJZpQ0/1skO36g+rocDAD8oADs=,iv:sbnCcahcRrP67L9ZH82y0OGxxS9zErBc45TbXp9dROI=,tag:HrR8MOu+8tqzmNOC/gEnrg==,type:str]
sops:
    shamir_threshold: 1
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nmdv4q8hcyj3s6qevrmc9w2vhd4a8tsj5j5e0cry5utex7vqeprslyjvxz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhT0ZkYVRXazdNN0JmQm91
            dlZweHpqK00xalBORE53em5SNjVUMDBwK2kwCm5lejA2aGxueHV2emREd2FTdHhJ
            V3dKWGZVcmlxTCtqaDFYdHlSdlFzZjQKLS0tIFZNVUtwdnFYcVFrc1I0ZXExMUo4
            eUN2ZnRaU0VzSXZDNlBBVFVyQ3lpaGMKAg7VUhl6DM3VLRwpmoIV3J9wkM96MC+r
            HapWenCJ0YXmw76JH/Poi7RQDsr1VSTTunpokASqsGexCKa7LPjNXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-20T21:10:38Z"
    mac: ENC[AES256_GCM,data:I3KxSUJa+czks5P9n8sVQe3cyGIJuwY+yS4u5p1paBiUiM3Fv22oUBNFh/+p2vCn2gKorsYLmsPfFI7XTX3QFAxD8xpsuU+v0GEXoTJ9qI5+0m6X6W3hkAr4JgULwwJMtgmeXu4ZBh2wY3YKlYS6FvOSdAIPg1O+gtVvt5+KGu0=,iv:nZ8928ocV4ZRMraXUNyaS0kYRCdrMedEuclpySd8AhA=,tag:lv1HAjX+O+S3p6Xi5AF2vA==,type:str]
    pgp:
        - created_at: "2024-01-20T21:10:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA82M54yws73UARAAsXvk5bbFcYLmGaultm9jgPn2q4sxtLpwOs+Mxx8ePm7+
            WJnwSiftweZ+p1ZYXLCWi3fPvUutnI4dsGfPeugSakUIGt1ly5jdjmY5vtfMk4Rl
            POBpmOqkqOToWHurunt2kQGb1qlLEh9lXotIWeyTnhnO44z6WZXhG/m7GH4JPCi/
            6jzPhIoc/Bqya18moG2yh6qP536P2DdxCLIqHfv+FOWBRzKjudeKW+UmDjrofnzD
            eVcrDeLX14efzW+KWLHGdH03Amy3wiNSMEvR2J6SSyKW4qdtiZNXc0mdev15cUNj
            kij2DFBxj15ACmkI5T0MCdokCYiutMQFmcp6DMzWDx+QNV2GD3pBZ7DrqpP/+oZg
            1rpfuJWSjL1IeiwwxpAmDTPpMUv5CRTU0YtMb0Vr8kLDsmj9+QdMYjkCBUcI6PDY
            7ipfcXMm6V23euj3NNd/001SsbO7R/KO+UZZ2CjvYd4hH77IJ65/STw94Zi5YAdk
            D1pk97x4moXCna2z2eIwF8xAInpm27eNyWDDteKhX7haMi3M+e5j5CRZra4XUuVE
            OFbtzzvvfxuImRb8fpE87gMadGhJAWWoFA4TlKtckNmrhKIeOTWeE2JnzjZEON/5
            ZKChof6s4K8lFHyQT8oo4DuJMsTN9JnngNRZgNATyysRNXpl4hmDCy/LJ1Mbh2LS
            XAGb19rTGO+HfJN8hQzED8OO+qWctWNK+/uXzcLPE4GWBewsEHtCxUOPcSThcuN0
            a6ok4QvjvdDo/1LUKkdlZsjx9MQLrQZLexLunZcqK7gzVxHmzhFCN8XcwgDQ
            =0PES
            -----END PGP MESSAGE-----
          fp: CD8CE78CB0B3BDD4
        - created_at: "2024-01-20T21:10:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMA2W9MER3HLb7AQf+Pd7EweWoLLwB9/efdE8TdyRLk0p92zXnhh48CYmsJhhf
            mFyv8JBdBCRqPItOd+yyBhF9lARb24GA9h51XgDBLvS+E2GN3pFpFBp8UNCPNp4W
            E3wk4Ps6YyeLwRFBfI8Lvd8pHDzGPdP4EURvDCogal6IDKMR0MFA1SYPGoj56MOM
            BQc1zcnKlIy2I+iC/hIkAyOLqD7jBaaiYoycwOZ/Hs+T9CxUyCnTapOWacj3dc/e
            frxqSDAG9K7j+dj2UZ3zxkVtC0FihA+j8A6MupL/GLoLgk1Y5NJ1H5l8z4WHjwhz
            rWp1d+0RHkE1zwv6j+Oy+MLcWpZ9FgsHvZ2wUgJoBdJcAWkR8wDDpflXHeWCJGIl
            q+4oTeCqmuG8vhLEaoU+PSnpSqD0PT9JpNkPLhFqmnjabex04KGjVacu/3FBjIHY
            XUF9Cfj9CVEJg3cwMGh+w6L/JbfUqsejhttkZMU=
            =NUfI
            -----END PGP MESSAGE-----
          fp: 65BD3044771CB6FB
    unencrypted_suffix: _unencrypted
    version: 3.8.1
