apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dex
  namespace: argocd
spec:
  project: system
  sources:
    - repoURL: "https://charts.dexidp.io"
      targetRevision: 0.15.*
      chart: dex
      helm:
        valuesObject:
          configSecret:
            name: dex-config
            create: false
          volumeMounts:
          - mountPath: /etc/ssl/certs
            name: etc-ssl-certs
            readOnly: true
          volumes:
          - name: etc-ssl-certs
            hostPath:
              path: /etc/dex-ssl
              type: DirectoryOrCreate
    - repoURL: "https://github.com/gensokyo-zone/infrastructure"
      path: k8s/system/dex/manifests
      targetRevision: main
  destination:
    namespace: dex
    name: in-cluster
  syncPolicy:
    syncOptions:
      - ServerSideApply=true