apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: system
  source:
    repoURL: "https://helm.traefik.io/traefik"
    targetRevision: v26.0.x
    chart: traefik
    helm:
      valuesObject:
        ports:
          traefik:
            expose: true
        service:
          spec:
              loadBalancerIP: "10.1.1.6"
  destination:
    namespace: kube-system
    name: in-cluster
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
  ignoreDifferences:
  - group: traefik.io
    kind: IngressRoute
    jsonPointers:
    - /metadata/annotations