apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: system
  source:
    repoURL: "https://helm.traefik.io/traefik"
    targetRevision: v26.0.x
    chart: traefik
    helm:
      valuesObject:
  destination:
    namespace: kube-system
    name: in-cluster
  syncPolicy:
    syncOptions:
      - ServerSideApply=true