apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    creationTimestamp: null
    name: dex-config
    namespace: dex
spec:
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:pZILaH34uFgX7A==,iv:I46DI6jjiRjG1UknTCNHWjodEqBkEOp/rI8kEkJvY/s=,tag:6mAsRl7LQQRu1QE0FwQbTQ==,type:str]
          data:
            config.yaml:
                storage:
                    type: ENC[AES256_GCM,data:39ge4Or5cDo=,iv:oARSgNoQ0sQQozIywUmYrm8m4sfPoECboMbaL1fmBsA=,tag:GYIvtM8zqxI1bqZwpeW8rQ==,type:str]
                    config:
                        host: ENC[AES256_GCM,data:11uXufAAko3Nbedw01vck2RgxSw5shVgwdHNEhC+,iv:0ZET8rdl4FR/36venH+6k9DvjfQr46bJDOtZ1S4FUdU=,tag:3M573xjYTa1qohK2rvdgCQ==,type:str]
                        port: ENC[AES256_GCM,data:6nzvaA==,iv:IHXm2tTQzM9F5MrBYitnRabjAF7hayVS7SNsqVbymik=,tag:LUzcpT1XrwwpbbtXvMjvzA==,type:int]
                        database: ENC[AES256_GCM,data:Yovw,iv:k3MH9Y2m0E9VOXtb/pwlxra9ctSTRCofhdmnwZE6yQ8=,tag:G/IjExV079eEKKBlS6+HiA==,type:str]
                        username: ENC[AES256_GCM,data:85qR,iv:t30jFTrKNm4ZvUKtEV3vpFGrfeeobWkrkZILd4Ci0Ww=,tag:zQPW+9CKfiv2uajnJx4wCg==,type:str]
                        password: ENC[AES256_GCM,data:vZFgE81MZQD1xCEMjp2KTI9lGd47ZWX7//21GJh3sF4=,iv:nQusG/NUeghYCc6pCD+4HbOWO/MeoPDQcjkvkt9plec=,tag:LlENPdV4rKCSNRLGxpoXAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nmdv4q8hcyj3s6qevrmc9w2vhd4a8tsj5j5e0cry5utex7vqeprslyjvxz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUlJzM3lrTVVwSmdEVHNF
            c2FlUlQ1MnJPZG9INmpQL1phZWFaQXFiMDB3Cnlnd2JEaE1yRURzWTZZMiszWnE3
            VitRTTF0ZXh4UVplaHRnTnJZRnloWGMKLS0tIEZSYm02eG1xNnhCeDVEY3ZNYnEy
            UnVLNEt5N1laMWcrRWF0RHNqY3pyUTAKURvlCLdILf5LgU8dmXTIsmTWOnimznv+
            Dd2iOWPfp//ZIxzRmDDLnIw+wQdB/JSClsVE+655G6YCS4y+lRproQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-21T21:10:06Z"
    mac: ENC[AES256_GCM,data:mhJPfZV9Q4e2sNHldq0Wc2K9XfN+SfrZBNoZDP0QLfPp5BG6vvxQ3kwZJd9MGtQ0WH+h8AY1UowzjfTm9eme4xEwELdEAMaZBS/Jd1nlcSyuAVm8Xs8acklhzNnBUkmzbY/IenzPDO5u5gELHy1CLA6aIfMMviEXDGNnSuNnlUM=,iv:Vg8qFElSTwZI/Y5pBX4DQhB6gxGCtrRy/Q0losYvvBc=,tag:x1kxeU1u9i1Re3BA2NdNlA==,type:str]
    pgp:
        - created_at: "2024-01-21T20:42:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA82M54yws73UAQ//RT5SDeyuUm4Q6vu0D8fhgqqKpW2xD47Zq0SWD49HeMPh
            EQ4MtKjWzV8u3C3b6US4okln5j04D/BuKXU07NASzsFlR9fyNyjarNIkMHrKDRYp
            y6Ho4f8mlWaS28SL5wAhQq0tkaK5J2O2dmI7ExHRaQezeyk6uAj+qbjZSng/sU/T
            4frAHT6LlOQrjfdsT62xOq4uRRu991DNkLk4Bk0CcaVYpYfVnVyezGH58yO1uSd3
            eoQ0KuNBOTPsI518RZT7YMJIo7abXiyCBJv7gEn6x2w+zXAVm9nDrDoloOAzn4W+
            e344pFPAJEeBzPtKtfTVAHgYao/CaWX6j6PJFfamo/Wo2zIafn7z+nbOWQMgiEqr
            EuKPV2wT4QntLBaA6ZQA4ifzZNJiDSgCAr6QcUurWNcN1nKwgU2nJXyT4j/SPk1G
            No0OYxaslylL7GpQoNBL9z5mXIL7R7XAaAhJAWBaYZgrb9XyQQ1YJa8IEV3ofIRm
            CKvtMBcWTAGnRVxP1jZk8y7ROgdyWQo5Tdt88j1sKOCGBlNPGEKKJIqxn9G2NW/O
            NqSAbCmIvg1fuYUQvom1eDM/nhvuTGNMF1t6Gf73ovDSYSiBF95vfUripR5jxUw6
            JFVAMz/qzpL97KIWMymJy+w3XZDgSYnNAhtbhpVGOg5tiO2olAVt+KWyQzpw6HPS
            XgFjluZwOdJGSUbGJpIdfXB81kVuVTTDLJSxkjV1y8iqpQN6t14W2caGZGVmwGBu
            CcpRqN1pp3kfLeNWCqbzfXt9yrnqZ32OqdBObbGniGYUPMRO2ssIsw+KKJ6zgyY=
            =ieT6
            -----END PGP MESSAGE-----
          fp: CD8CE78CB0B3BDD4
        - created_at: "2024-01-21T20:42:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMA2W9MER3HLb7AQf9GMt2t0wNFZRDN50QW0dbVnKXZ8ky3b6M4mM5CHZkbgtb
            bfOLr8Z4YvyBqNyvfHtE9JnCmCnFHyllM2u8ft0WKdk1RBT8HLKYiVg3Lr4jQ5Vn
            oIIn1s5zIBPb9BF+NgT0M2LW9BRkDgXcdJFShNhXl4pqTN/TB2I0BmtvcHNaXk/1
            TqbESWsbAymdZ73UYtKp5McZM/0OMcOQ3j3Rh5gzkz9/8UKp19jQDNnU4MA6iUuN
            G+m8FjFn8PHvWyDhDlLSQI14fgKEGKx1reyaYEQxecIl/r4B/T2BdWEP56Zdaa3u
            70T+1a0NpPrD8cwkHX+IxZOWtRpDdD5+AnzeNDdHvNJeASO8Bwa8yN3hrzXwtWTu
            Qbu0+8xTCoGrQjKmE4y9sR3bE99T0uEjrqxF1qfE9MIKK/lNMGf2Z+A8Le/v2Jg5
            lVIfySQe9EaLVcuKkfqnGSBLZWoOjqlfRfBL118prw==
            =yZNj
            -----END PGP MESSAGE-----
          fp: 65BD3044771CB6FB
    encrypted_suffix: Templates
    version: 3.8.1
