apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sops-secrets-operator
  namespace: argocd
spec:
  project: system
  source:
    repoURL: "https://isindir.github.io/sops-secrets-operator/"
    targetRevision: 0.18.0
    chart: sops-secrets-operator
    helm:
      valuesObject:
        secretsAsFiles:
          - mountPath: /etc/sops-age-key-file
            secretName: sops-age-key-file
        extraEnv:
          - name: SOPS_AGE_KEY_FILE
            value: /etc/sops-age-key-file/sops.key
  destination:
    namespace: sops
    name: in-cluster
  syncPolicy:
    syncOptions:
      - ServerSideApply=true