server:
    listen: 0.0.0.0@53
    listen: ::@53

remote:
  - id: benjojo
    address: 185.230.223.84
    address: 2a0c:2f07:4896:666:216:3eff:fedb:c742

acl:
  - id: update_acl
    key: dnsupdate
    address: 0.0.0.0/0
    address: ::/0
    action: update
  - id: benjojo_acl
    remote: benjojo
    action: transfer

zone:
  - domain: kittywit.ch
    semantic-checks: on
    storage: /var/lib/knot/zones/
    file: kittywit.ch.zone
    dnssec-signing: on
    notify: benjojo
    acl: [ benjojo_acl, update_acl ]

log:
  - target: syslog
    any: info
